CREATE TABLE CLIENT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    CPF VARCHAR (11)
);

CREATE TABLE PRODUCT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    UNITY_PRICE NUMERIC (20, 2)
);

CREATE TABLE SOLICITATION(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES CLIENT (ID),
    SOLICITED_AT TIMESTAMP,
    STATUS VARCHAR(20),
    TOTAL NUMERIC(20, 2)
);

CREATE TABLE SOLICITED_ITEM(
    ID INTEGER  PRIMARY  KEY  AUTO_INCREMENT,
    SOLICITATION_ID INTEGER REFERENCES SOLICITATION (ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT (ID),
    QUANTITY INTEGER
);